- name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4 
- name: build
        run : sudo npm i yarn -g && yarn install && yarn electron:build-linux arm64 deb
 
      - uses: actions/upload-artifact@v2
        with:
          name: YesPlayMusic-linux
          path: dist_electron/*.deb
          if-no-files-found: ignore
