name: Build / Release

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install RPM & Pacman (on Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y rpm &&
          sudo apt-get install --no-install-recommends -y bsdtar &&
          sudo apt-get install --no-install-recommends -y libopenjp2-tools
      - name: Install Snapcraft (on Ubuntu)
        uses: samuelmeuli/action-snapcraft@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
          
      - name: build
        run : npm i electron-builder -g && electron-builder -l --arm64 deb
 
      - uses: actions/upload-artifact@v2
        with:
          name: YesPlayMusic-linux
          path: dist_electron/*.deb
          if-no-files-found: ignore
